import atomic from './atomic.jpg'
import thehabit from './Thehabit.png'
const catalog = [
    {
      id: 1,
      title: "Atomic habit",
      author: "Author 1",
      description: "Description of Book 1",
      coverImage: atomic,
      price: 9.99,
      ratings: 4.5,
      category: "Fiction",
      publicationDate: "2022-01-01",
    },
    {
      id: 2,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 3,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 4,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 5,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 6,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 7,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 8,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 9,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 10,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 11,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
    {
      id: 12,
      title: "The Habit",
      author: "Author 2",
      description: "Description of Book 2",
      coverImage: thehabit,
      price: 14.99,
      ratings: 4.2,
      category: "Non-fiction",
      publicationDate: "2021-06-15",
    },
  ];
  
  export default catalog;
  